name: Generate terraform docs
on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        ref: ${{ github.event.pull_request.head.ref }}

    - name: Render terraform docs for app_infra and push changes back to PR
      uses: terraform-docs/gh-actions@main
      with:
        working-dir: app_infra
        output-file: README.md
        output-method: inject
        git-push: "true"

    - name: Render terraform docs for db_infra and push changes back to PR
      uses: terraform-docs/gh-actions@main
      with:
        working-dir: db_infra
        output-file: README.md
        output-method: inject
        git-push: "true"
